config/routes.rb
TvNotifier::Application.routes.draw do

  resources :list_shows

  root :to => 'shows#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :shows

end

app/models/list_show.rb
class ListShow < ActiveRecord::Base
  belongs_to :show
  belongs_to :user

  attr_accessible :show_id, :user_id
end

app/controllers/list_shows_controller.rb
class ListShowsController < ApplicationController
  # GET /list_shows
  # GET /list_shows.json
  def index
    @list_shows = ListShow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list_shows }
    end
  end

  # GET /list_shows/1
  # GET /list_shows/1.json
  def show
    @list_show = ListShow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_show }
    end
  end

  # GET /list_shows/new
  # GET /list_shows/new.json
  def new
    @list_show = ListShow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list_show }
    end
  end

  # GET /list_shows/1/edit
  def edit
    @list_show = ListShow.find(params[:id])
  end

  # POST /list_shows
  # POST /list_shows.json
  def create
    @user = User.find_by_id(session[:user_id])
    show = Show.find(params[:show_id])
    @list_show = @user.list_shows.build
    @list_show.show = show
    #@list_show = ListShow.new(params[:list_show])

    respond_to do |format|
      if @list_show.save
        format.html { redirect_to shows_path, notice: "#{show.title} was added to list." }
        format.json { render json: @list_show, status: :created, location: @list_show }
      else
        format.html { render action: "new" }
        format.json { render json: @list_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list_shows/1
  # PUT /list_shows/1.json
  def update
    @list_show = ListShow.find(params[:id])

    respond_to do |format|
      if @list_show.update_attributes(params[:list_show])
        format.html { redirect_to @list_show, notice: 'List was updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_shows/1
  # DELETE /list_shows/1.json
  def destroy
    @list_show = ListShow.find(params[:id])
    @list_show.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/list_shows_helper.rb
module ListShowsHelper
end

app/views/list_shows/_form.html.erb
<%= form_for(@list_show) do |f| %>
  <% if @list_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_show.errors.count, "error") %> prohibited this list_show from being saved:</h2>

      <ul>
      <% @list_show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :show_id %><br />
    <%= f.number_field :show_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_shows/edit.html.erb
<h1>Editing list_show</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_show %> |
<%= link_to 'Back', list_shows_path %>

app/views/list_shows/index.html.erb
<h1>Listing list_shows</h1>

<table>
  <tr>
    <th>Show</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_shows.each do |list_show| %>
  <tr>
    <td><%= list_show.show_id %></td>
    <td><%= list_show.user_id %></td>
    <td><%= link_to 'Show', list_show %></td>
    <td><%= link_to 'Edit', edit_list_show_path(list_show) %></td>
    <td><%= link_to 'Destroy', list_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List show', new_list_show_path %>

app/views/list_shows/new.html.erb
<h1>New list_show</h1>

<%= render 'form' %>

<%= link_to 'Back', list_shows_path %>

app/views/list_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Show:</b>
  <%= @list_show.show_id %>
</p>

<p>
  <b>User:</b>
  <%= @list_show.user_id %>
</p>


<%= link_to 'Edit', edit_list_show_path(@list_show) %> |
<%= link_to 'Back', list_shows_path %>